<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="pascalito" nsURI="http://www.example.org/pascalito" nsPrefix="pascalito">
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Programa">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Ident" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bloco" lowerBound="1" eType="#//Bloco"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Bloco">
    <eStructuralFeatures xsi:type="ecore:EReference" name="defvariavel" upperBound="-1"
        eType="#//Variavel" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="defprocedimento" upperBound="-1"
        eType="#//Procedimento" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="executa" upperBound="-1"
        eType="#//Comando" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CallVariavel" eSuperTypes="#//Expressao">
    <eStructuralFeatures xsi:type="ecore:EReference" name="representa" lowerBound="1"
        eType="#//Variavel"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Comando" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="CallProcedimento" eSuperTypes="#//Comando">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="numeroParametros"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="numeroParametros" value="self.definido.parametro->size() = parametro->size()"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="definido" lowerBound="1"
        eType="#//Procedimento"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parametro" upperBound="-1"
        eType="#//Expressao" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Atribuicao" eSuperTypes="#//Comando">
    <eStructuralFeatures xsi:type="ecore:EReference" name="atribui" lowerBound="1"
        eType="#//Variavel"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="atribuiResultado" lowerBound="1"
        eType="#//Expressao" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Desvio" eSuperTypes="#//Comando">
    <eStructuralFeatures xsi:type="ecore:EReference" name="se" lowerBound="1" eType="#//Expressao"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="faca" upperBound="-1" eType="#//Comando"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="seNao" upperBound="-1"
        eType="#//Comando" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Loop" eSuperTypes="#//Comando">
    <eStructuralFeatures xsi:type="ecore:EReference" name="se" lowerBound="1" eType="#//Expressao"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="faca" upperBound="-1" eType="#//Comando"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expressao" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//Expressao"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//Expressao"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExpBinLogica" eSuperTypes="#//Expressao"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExpNeg" eSuperTypes="#//Expressao">
    <eStructuralFeatures xsi:type="ecore:EReference" name="nega" lowerBound="1" eType="#//Expressao"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="newRole15">
    <eAnnotations source="http://www.obeo.fr/dsl/dnc/archetype">
      <details key="archetype" value="Role"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Variavel">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Tipo" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Valor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Procedimento">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bloco" lowerBound="1" eType="#//Bloco"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parametro" upperBound="-1"
        eType="#//Variavel" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CallProc" eSuperTypes="#//Expressao">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="numeroParametros"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="numeroParametros" value="self.representaProc.parametro->size() = parametro->size()"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="representaProc" lowerBound="1"
        eType="#//Procedimento"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parametro" upperBound="-1"
        eType="#//Expressao" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="N_Comutativa" eSuperTypes="#//Expressao"/>
  <eClassifiers xsi:type="ecore:EClass" name="Comutativa" eSuperTypes="#//Expressao"/>
  <eClassifiers xsi:type="ecore:EClass" name="NumberLiteral" eSuperTypes="#//Expressao"/>
</ecore:EPackage>
